### ISSUE TITLE
Lists that don't need parsing don't make it through

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/piholeparser#4]
Lists that are already in the correct format aren't making it through the parser.

It doesn't make sense.

I believe that the lists shouldn't be parsed with a "one-liner" and that it should be a step by step process.

the parser needs to work universally on every list.

**Comment by TheAntimist** [comment]
I had the same issue with my parser script, it's mostly due to the perl script or the shell script matching of the form `||URL$` or something like that. which doesn't match the preparsed scripts. In my case, I skipped out and had a separate list for ones which didn't require parsing. And just parsed them separately.

**Comment by deathbybandaid** [comment]
I'm working on filtering the lists one step at a time, and avoiding that issue. 

If you have any ideas, let me know

**Comment by deathbybandaid** [comment]
I created a "light" parser and split the lists into two folders. this should work better.
